### PR TITLE
add corr check argument

### PR DESCRIPTION
**Pull request by maxsal**

### CODE REVIEW

**Review by maxsal — COMMENTED** [review]
in R/check_for_data_correction.R, min_count should be applied to the previous days count (i.e., dplyr::lag(v))

**Review by maxsal — COMMENTED** [review]
in R/get_r0.R, the corr_check should be TRUE by default, no? We want to remove observations that qualify as data correction observations.

After thinking more, we're just setting the default to FALSE but it's inheriting the corr_check argument in get_metrics_tables, which is corr_check = TRUE by default, correct?

**Comment by mkleinsa** [comment]
The call to get_r0 in get_all_data is not currently being fed an argument, meaning that corr_check = FALSE is being used, then, at the bottom of get_all_data we're doing some stuff to account for correction. Are those two separate corrections? I am referring to  https://github.com/maxsal/covid19india/blob/deb0ac02fca6de26a48236785505067a3c472419/R/get_all_data.R#L33 and  https://github.com/maxsal/covid19india/blob/deb0ac02fca6de26a48236785505067a3c472419/R/get_all_data.R#L76.

**Comment by maxsal** [comment]
The corr check should come here:

https://github.com/maxsal/covid19india/blob/deb0ac02fca6de26a48236785505067a3c472419/R/get_all_data.R#L33

Not at end. Though this would remove observations from the resulting dataset. Perhaps we should have corr_check run in the get_r0 function?

**Comment by maxsal** [comment]
good to go

**Pull request merged**
